@extends('layouts.app')
@section('title', 'Demand Forecast')
@section('content')
<h2>📈 Demand Forecast — {{ $crop }}</h2>
<div class="card">
    <form method="GET" action="{{ route('supplier.demand-forecast') }}">
        <label>Crop name</label>
        <input type="text" name="crop" value="{{ $crop }}">
        <button type="submit" class="btn-primary" style="margin-top:10px;">View</button>
    </form>

    @if (isset($forecast['forecast_bdt_per_kg']))
        <div class="result-box">
            <strong>Current price: <span class="mono">৳{{ $forecast['last_known_price_bdt_per_kg'] }}/kg</span></strong>
            <p>Next 3 months: <span class="mono">৳{{ implode(', ৳', $forecast['forecast_bdt_per_kg']) }}</span></p>
        </div>
    @elseif (isset($forecast['error']))
        <div class="result-box">
            <p class="muted">{{ $forecast['error'] }} — supported crops right now: rice, maize, cotton, jute, banana, mango, coffee, coconut.</p>
        </div>
    @endif
</div>

<div class="card">
    <h3>Platform-wide Demand Forecasts</h3>
    <table class="data-table">
        <thead><tr><th>Category</th><th>Zone</th><th>Period</th><th>Predicted Demand</th></tr></thead>
        <tbody>
        @forelse ($storedForecasts as $f)
            <tr><td>{{ $f->category }}</td><td>{{ $f->zone->zone_name }}</td><td>{{ $f->forecast_period }}</td><td class="mono">{{ $f->predicted_demand_units }}</td></tr>
        @empty
            <tr><td colspan="4" class="muted">No data yet (generated by the admin/ML pipeline).</td></tr>
        @endforelse
        </tbody>
    </table>
</div>
@endsection
